### ISSUE TITLE
Error building `CodecZlib`

### ISSUE THREAD

**Issue by trecakov** [bicycle1885/CodecZlib.jl#38] opened 2018-12-22 16:29 UTC
I am getting this error:

```
julia> Pkg.build("CodecZlib")
  Building CodecZlib → `~/.julia/packages/CodecZlib/DAjXH/deps/build.log`
┌ Error: Error building `CodecZlib`:
│ ERROR: LoadError: IOError: could not spawn `/software/packages/julia/julia-1.0.2/bin/julia -Cnative -J/software/packages/julia/julia-1.0.2/lib/julia/sys.so --compile=yes --depwarn=yes -O0 --output-ji /home/trecakov/.julia/compiled/v1.0/BinaryProvider/ek6VZ.ji --output-incremental=yes --startup-file=no --history-file=no --warn-overwrite=yes --color=no --eval "while !eof(stdin)
│     code = readuntil(stdin, '\0')
│     eval(Meta.parse(code))
│ end
│ "`: resource temporarily unavailable (EAGAIN)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{Base.PipeEndpoint,RawFD,RawFD}) at ./process.jl:367
│  [2] (::getfield(Base, Symbol("##494#495")){Cmd})(::Tuple{Base.PipeEndpoint,RawFD,RawFD}) at ./process.jl:509
│  [3] setup_stdio(::getfield(Base, Symbol("##494#495")){Cmd}, ::Tuple{Pipe,IOStream,IOStream}) at ./process.jl:490
│  [4] #_spawn#493(::Nothing, ::Function, ::Cmd, ::Tuple{Pipe,IOStream,IOStream}) at ./process.jl:508
│  [5] (::getfield(Base, Symbol("#kw##_spawn")))(::NamedTuple{(:chain,),Tuple{Nothing}}, ::typeof(Base._spawn), ::Cmd, ::Tuple{Pipe,IOStream,IOStream}) at ./none:0
│  [6] #_spawn#490(::Nothing, ::Function, ::Base.CmdRedirect, ::Tuple{Pipe,IOStream,IOStream}) at ./process.jl:398
│  [7] _spawn(::Base.CmdRedirect, ::Tuple{Pipe,IOStream,IOStream}) at ./process.jl:398
│  [8] #open#503(::Bool, ::Bool, ::Function, ::Base.CmdRedirect, ::IOStream) at ./process.jl:599
│  [9] #open at ./none:0 [inlined]
│  [10] open(::Base.CmdRedirect, ::String, ::IOStream) at ./process.jl:567
│  [11] create_expr_cache(::String, ::String, ::Array{Pair{Base.PkgId,UInt64},1}, ::Base.UUID) at ./loading.jl:1111
│  [12] macro expansion at ./logging.jl:306 [inlined]
│  [13] compilecache(::Base.PkgId, ::String) at ./loading.jl:1190
│  [14] _require(::Base.PkgId) at ./logging.jl:309
│  [15] require(::Base.PkgId) at ./loading.jl:858
│  [16] macro expansion at ./logging.jl:309 [inlined]
│  [17] require(::Module, ::Symbol) at ./loading.jl:840
│  [18] include at ./boot.jl:317 [inlined]
│  [19] include_relative(::Module, ::String) at ./loading.jl:1044
│  [20] include(::Module, ::String) at ./sysimg.jl:29
│  [21] include(::String) at ./client.jl:392
│  [22] top-level scope at none:0
│ in expression starting at /home/trecakov/.julia/packages/CodecZlib/DAjXH/deps/build.jl:1
└ @ Pkg.Operations /software/packages/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

Any suggestions?

**Comment by damiansp** [comment] 2019-01-24 17:18
Having a similar issue: (Julia 1.0.0; Mac OSX Mojave/10.14)
```
julia> Pkg.build("CodecZlib")

  Building CodecZlib → `~/.julia/packages/CodecZlib/DAjXH/deps/build.log`
┌ Error: Error building `CodecZlib`: 
│ [ Info: Downloading https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.3/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz to /Users/dsp/.julia/packages/CodecZlib/DAjXH/deps/usr/downloads/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz...
│ ERROR: LoadError: Could not download https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.3/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz to /Users/dsatterthwaite/.julia/packages/CodecZlib/DAjXH/deps/usr/downloads/Zlib.v1.2.11.x86_64-apple-darwin14.tar.gz:
│ ErrorException("")
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] macro expansion at ./logging.jl:313 [inlined]
│  [3] #download#89(::Bool, ::Function, ::String, ::String) at /Users/dsp/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:487
│  [4] #download at ./none:0 [inlined]
│  [5] #download_verify#90(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /Users/dsp/.julia/packages/BinaryProvider/4F5Hq/src/PlatformEngines.jl:567
│  [6] #download_verify at ./none:0 [inlined]
│  [7] #install#129(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /Users/dsp/.julia/packages/BinaryProvider/4F5Hq/src/Prefix.jl:314
│  [8] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [9] top-level scope at logging.jl:309
│  [10] top-level scope at /Users/dsp/.julia/packages/CodecZlib/DAjXH/deps/build.jl:82
│  [11] include at ./boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at ./loading.jl:1038
│  [13] include(::Module, ::String) at ./sysimg.jl:29
│  [14] include(::String) at ./client.jl:388
│  [15] top-level scope at none:0
│ in expression starting at /Users/dsp/.julia/packages/CodecZlib/DAjXH/deps/build.jl:78
│ [09:09:36] curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

**Comment by bicycle1885** [comment] 2019-03-29 05:50
I think this will be solved by https://github.com/JuliaLang/julia/pull/30969. Forgive me to close this issue because this is not caused by this package.

**Closed as completed by bicycle1885** 2019-03-29 05:50 UTC
